# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# ------------------------------------------------
# check static files
# ------------------------------------------------
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: pretty-format-json
        args: [--autofix]

- repo: https://github.com/markdownlint/markdownlint
  rev: v0.12.0
  hooks:
    - id: markdownlint
      # ignore line length of markdown
      args: [-r, ~MD013]


# ------------------------------------------------
# check Python file
# ------------------------------------------------
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    # max-line-length setting is the same as black
    # commit cannot be done when cyclomatic complexity is more than 10.
    args: [--count, --exit-zero, --max-complexity=10, --max-line-length=127, --statistics]
    additional_dependencies: [flake8-bugbear, flake8-builtins, flake8-eradicate, pep8-naming, flake8-expression-complexity, flake8-cognitive-complexity]
